export const names: string[] = [
  'finish the CV',
  'do the Clock task',
  'do the Goods Selector task',
  'do the Counter task',
  'spend your weekends as a weekends(joke)',
  'do the List of Goods task',
  'complete overdue morning tasks',
  'practice English',
  'have some rest(joke)',
  'improve typing speed',
  'do expired laboratory works in physics',
  'do expired laboratory works in programming',
  'do expired laboratory works in IT',
  'complete overdue individual math homeworks',
  'defend course work on programming',
  'to die in peace(joke)',
  'prepare for the physics exam',
  'prepare for the math exam',
  'prepare for the exam in mathematical methods',
  'see your friends (joke)',
  'get prepared for technical check',
];
